# Project: Project2
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = RunGL.o cpp/ARB_Multisample.o $(RES)
LINKOBJ  = RunGL.o cpp/ARB_Multisample.o $(RES)
LIBS =  -L"lib" -mwindows 0_0_1_AA_commonLib/fmod.lib 0_0_1_AA_commonLib/FreeImage.lib 0_0_1_AA_commonLib/libEGL.lib 0_0_1_AA_commonLib/libopengl32.a 0_0_1_AA_commonLib/libwinmm.a  
INCS =  -I"include"  -I"C:/Imagination/PowerVR/GraphicsSDK/SDK_3.0/Shell"  -I"C:/Imagination/PowerVR/GraphicsSDK/SDK_3.0/Tools/OGLES2" 
CXXINCS =  -I"lib/gcc/mingw32/3.4.2/include"  -I"include/c++/3.4.2/backward"  -I"include/c++/3.4.2/mingw32"  -I"include/c++/3.4.2"  -I"include"  -I"C:/Imagination/PowerVR/GraphicsSDK/SDK_3.0/Shell"  -I"C:/Imagination/PowerVR/GraphicsSDK/SDK_3.0/Tools/OGLES2" 
BIN  = LITTLE_GREEN_MEN.exe
CXXFLAGS = $(CXXINCS) -Wno-deprecated  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before LITTLE_GREEN_MEN.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "LITTLE_GREEN_MEN.exe" $(LIBS)

RunGL.o: RunGL.cpp
	$(CPP) -c RunGL.cpp -o RunGL.o $(CXXFLAGS)

cpp/ARB_Multisample.o: cpp/ARB_Multisample.cpp
	$(CPP) -c cpp/ARB_Multisample.cpp -o cpp/ARB_Multisample.o $(CXXFLAGS)
