# Project: Project2
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o load_3ds.o load_bmp.o mat_vect.o object.o $(RES)
LINKOBJ  = main.o load_3ds.o load_bmp.o mat_vect.o object.o $(RES)
LIBS =  -L"Z:/Volumes/BOOTCAMP/Dev-Cpp/lib" C:/users/marcdion/Desktop/_NEW_MIXED_02_C/!_0_MARBLE_MAZE_ROOM_04/0_0_1_AA_commonLib/FreeImage.lib C:/users/marcdion/Desktop/_NEW_MIXED_02_C/!_0_MARBLE_MAZE_ROOM_04/0_0_1_AA_commonLib/libglaux.a C:/users/marcdion/Desktop/_NEW_MIXED_02_C/!_0_MARBLE_MAZE_ROOM_04/0_0_1_AA_commonLib/libglu32.a C:/users/marcdion/Desktop/_NEW_MIXED_02_C/!_0_MARBLE_MAZE_ROOM_04/0_0_1_AA_commonLib/libglut32.a C:/users/marcdion/Desktop/_NEW_MIXED_02_C/!_0_MARBLE_MAZE_ROOM_04/0_0_1_AA_commonLib/libopenal32.a C:/users/marcdion/Desktop/_NEW_MIXED_02_C/!_0_MARBLE_MAZE_ROOM_04/0_0_1_AA_commonLib/libopengl32.a C:/users/marcdion/Desktop/_NEW_MIXED_02_C/!_0_MARBLE_MAZE_ROOM_04/0_0_1_AA_commonLib/libwinmm.a  
INCS =  -I"Z:/Volumes/BOOTCAMP/Dev-Cpp/include" 
CXXINCS =  -I"Z:/Volumes/BOOTCAMP/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"Z:/Volumes/BOOTCAMP/Dev-Cpp/include/c++/3.4.2/backward"  -I"Z:/Volumes/BOOTCAMP/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"Z:/Volumes/BOOTCAMP/Dev-Cpp/include/c++/3.4.2"  -I"Z:/Volumes/BOOTCAMP/Dev-Cpp/include" 
BIN  = vertexNormalSmoothing.exe
CXXFLAGS = $(CXXINCS) -Wno-deprecated  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before vertexNormalSmoothing.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "vertexNormalSmoothing.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

load_3ds.o: load_3ds.cpp
	$(CPP) -c load_3ds.cpp -o load_3ds.o $(CXXFLAGS)

load_bmp.o: load_bmp.cpp
	$(CPP) -c load_bmp.cpp -o load_bmp.o $(CXXFLAGS)

mat_vect.o: mat_vect.cpp
	$(CPP) -c mat_vect.cpp -o mat_vect.o $(CXXFLAGS)

object.o: object.cpp
	$(CPP) -c object.cpp -o object.o $(CXXFLAGS)
